install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - ./run 'cd 0.10.34 && docker build -t moul/strongloop . && docker run moul/strongloop echo Build succeed'
  - ./run 'cd 0.10.34-onbuild && docker build -t moul/strongloop . && docker run moul/strongloop echo Build succeed'
